trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: build
    jobs:
      - job: "build"
        displayName: build job
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"
          - script: |
              npm install
              npm run build --if-present
            displayName: "npm install, build"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/build"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: deploy
    displayName: "Deploy to the dev environment"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: "Pay-As-You-Go(1)(91a7faa1-dc40-4598-ac09-d72f572c347a)"
                    appType: "webAppLinux"
                    WebAppName: "react-yaml-dev"
                    packageForLinux: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
                    StartupCommand: "pm2 serve /home/site/wwwroot/ --no-daemon --spa"
                    AppSettings: "-REACT_APP_ENVIRONMENT_PROD PRODUCTION -REACT_APP_ENVIRONMENT_LOCAL LOCAL APP_ENV TEST"
