name: test_pipeline

on:
  # to trigger workflow manually
  workflow_dispatch:

  # to trigger workflow on code push
  push:
    branches:
      - master
  # to trigger workflow on PRs
  pull_request:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      # check out the repository
      - uses: actions/checkout@v4

      # single line comment
      - name: script single line
        run: echo "hello world!"

      # multi line comments
      - name: script multiple lines
        run: |
          echo "hi!!!!"
          echo "hello world!"
